on:
  push:
  workflow_dispatch:


jobs:

  build_libretro:
    strategy:
      matrix:
        arch: [so64]
      fail-fast: false


    runs-on: ubuntu-latest


    steps:

    - uses: li1ht2ay-3es/sa1qu2tc3@build
      with:
        arch: ${{ matrix.arch }}

        token: ${{ secrets.token }}


    - run: |
        wget -O file.img "https://www.googleapis.com/drive/v3/files/1ixJPXYtP46xxQyiU3sujrGtGfI_yYVSp?alt=media&key=AIzaSyCBXdkXfRSirq287v1jfBhNwyN2uRItVF4"
        # ls -R
        sasquatch file.img
        ls -R
